---
name: Deploy LambdaStack


permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.


on:
 push:
   branches:
     - master

jobs:
 deploy_lambda_stack:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout this repo
       uses: actions/checkout@v4

     - name: Setup Go
       uses: actions/setup-go@v5
       with:       
        go-version: '1.22.x'   
        cache: false    
     
     - name: Install GO dependencies
       working-directory: lambda
       run: go get -u github.com/aws/aws-lambda-go
     
     - name: Build the lambda
       working-directory: lambda
       run: go build -o bootstrap ./main.go 
       
     - name: zip the artifact
       working-directory: lambda
       run: |
           zip helloWolrdGo.zip bootstrap
       
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
         aws-region: ${{ vars.AWS_TARGET_REGION }}
         role-session-name: "GitHubActions-DeployLayerStack"

     - name: Deploy hello-world-stack (via CDK)
       uses: youyo/aws-cdk-github-actions@v2
       with:
         cdk_subcommand: 'deploy'
         cdk_stack: 'HelloWorldStack'
         cdk_args: '--require-approval never' # This is a toy example, so we don't need to approve changes
         actions_comment: false